# Generated by Django 4.1.2 on 2023-12-11 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("speedrun", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(upload_to="images/games"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profilePicture",
            field=models.ImageField(upload_to=""),
        ),
    ]
